### ISSUE TITLE
Config 파일 server 블록의 listen 지시어 파싱 수정

### ISSUE THREAD

**Issue by Jiwon-Woo** [FT-369/Webserv#12]
## Description

> Config 파일 server 블록의 listen 지시어 파싱 방법을 수정합니다

### 현재 파싱 방법
`listen [arg1] [arg2]` -> arg1은 port, arg2는 host로 파싱
`listen [arg1]` -> arg1은 port로 파싱

## To Do
`listen [arg1] [arg2]` -> 실제로 두번째 인자는 옵션과 관련, 옵션까지 할 필요 없으므로 에러 처리
`listen [arg1]` -> 양식에 따라 3가지로 파싱

- [x] `listen 80` -> `arg1` 이 정수인 경우 port로 파싱
- [x] `listen 127.0.0.1` -> `arg1` 이 주소 형식인 경우 host로 파싱
- [x] `listen 127.0.0.1:8080` -> `arg1` 에 `:`가 포함된 경우 `[host]:[port]`로 파싱

**Comment by kyoshong** [comment]
굿굿
